[build]
  command = "npm run build"
  publish = "out"
  base = "/"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.20.8"
  NEXT_TELEMETRY_DISABLED = "1"

# For a static export we don't need the Netlify Next.js plugin
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 